### PR TITLE
Exclude gnu.testlet.java.net.http url connection.request properties test

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
- Exclude gnu.testlet.java.net.http url connection.request properties test
- Related to openj9/issues/14168

Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test : Grinder/20028

**Comment by Mesbah-Alam** [comment]
@Peter_Shipton@ca.ibm.com - please review.

**Comment by pshipton** [comment]
Does it need to be excluded for all versions when it works up to and including jdk17, or can it be excluded for jdk18 and later?

**Comment by Mesbah-Alam** [comment]
> or can it be excluded for jdk18 and later? 

The only way to do that is to have separate load configuration xml files. We went that route in the past and ended up having to maintain a host of different configuration files for different versions. We subsequently decided to stop doing that. 

Also, since these mauve tests are primarily used to stress the JVM as "load tests", our focus has been to have a load that works on all versions.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
