### PR TITLE
Update references from AdoptOpenJDK to adoptium

### PR DESCRIPTION
**Pull request by keithc-ca**
The first commit only affects whitespace:
* indent reasonably and consistently
* remove trailing whitespace
* collapse multiple blank lines to one
* use CR/LF for *.bat and *.cmd files

The second updates references from AdoptOpenJDK to adoptium:
* openjdk-systemtest is now aqa-systemtest
* rename scripts accordingly

### CODE REVIEW

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
We had done a bunch of these clean ups few months back, but obviously these were missed. Thanks @keithc-ca !

**Comment by keithc-ca** [comment]
What am I intended to take from this being 'assigned' to me?

**Comment by Mesbah-Alam** [comment]
> What am I intended to take from this being 'assigned' to me? 

Since you authored this PR, it should be assigned to you - that was my thinking.

**Comment by keithc-ca** [comment]
I think it makes more sense to assign it to someone that has permission to (review and) merge it - that isn't me. ;-)

**Comment by Mesbah-Alam** [comment]
PR looks good :  Grinder/17594

**Pull request merged**
