### PR TITLE
Replace references of openjdk-systemtest with aqa-systemtest

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Related to : https://github.com/adoptium/aqa-systemtest/issues/424

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Works fine in non-parallel build. Sanity.jck green: Test_grinder/job/Grinder/14986/

**Comment by Mesbah-Alam** [comment]
Tests: 
- sanity.jck (with parallel = 6) - Grinder/15334/ - green
- extended.system (with parallel = 4) - Grinder/15328/ - green

**Comment by llxia** [comment]
Please note all 4 PRs have to merged together:
adoptium/STF#115
adoptium/aqa-systemtest#425
eclipse-openj9/openj9-systemtest#129
adoptium/aqa-tests#2542

**Comment by karianna** [comment]
Setting to draft so that we all go together.

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM

**Pull request merged**
